name: Deploy development documentation
on:
  push:
    branches:
    - dev
    paths-ignore:
      - '**.md'
      - '**.yml'

jobs:
  deploy-docs:
    name: Build and deploy documentation
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      env:
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL: True
      run: |
        python -m pip install --upgrade "pip<24.1" "setuptools==73.0.1"
        if [ -f docker_requirements.txt ]; then pip install -r docker_requirements.txt; fi
        python -m pip install .[full]
        python -m pip install boto smart_open sphinx sphinx-rtd-theme
    - name: Build sphinx documentation
      run: |
        cd docs && make html
        cd ..
    - name: Deploy documentation
      uses: peaceiris/actions-gh-pages@v4
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ./docs/_build/html
        external_repository: PyThaiNLP/dev-docs
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
