name: Lint

on:
  push:
    branches:
      - dev
    paths-ignore:
      - '**.md'
      - '**.yml'
      - 'docs/**'
  pull_request:
    branches:
      - dev
    paths-ignore:
      - '**.md'
      - '**.yml'
      - 'docs/**'

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Ruff
      uses: astral-sh/ruff-action@v3
      with:
        src: "./pythainlp"
        args: check --verbose --line-length 79 --select C901
