# SPDX-FileCopyrightText: 2016-2024 PyThaiNLP Project
# SPDX-License-Identifier: CC0-1.0

name: Build and publish to PyPI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  build:
    name: Build and check distributions
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[cd build]')
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install --upgrade build pip twine

    - name: Build source distribution and wheels
      run: python -m build

    - name: Check distributions
      run: twine check dist/*

    - name: Store distributions
      uses: actions/upload-artifact@v3
      with:
        path: pythainlp/dist/*

  publish_pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
    - name: Retrieve distributions
      uses: actions/download-artifact@v3
      with:
        name: artifact
        path: dist
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      if: github.event_name == 'release' && github.event.action == 'published'
      with:
        skip-existing: true
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
