name: Upload package to PyPI

on:
  release:
    types: [created]

jobs:
  pypi-publish:

    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade "pip<24.1" setuptools twine wheel
        python setup.py sdist bdist_wheel
      # "python setup.py" is no longer recommended.
    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
