name: Unit test and code coverage (MacOS)

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.yml'
      - 'docs/**'
  pull_request:
    branches:
      - dev
    paths-ignore:
      - '**.md'
      - '**.yml'
      - 'docs/**'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest"]
        python-version: ["3.9"]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install build tools
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade "pip<24.1" setuptools
        python -m pip install coverage coveralls pytest
    - name: Install ICU
      shell: bash -l {0}
      run: |
        brew install icu4c
        PKG_CONFIG_PATH=$(brew --prefix)/opt/icu4c/lib/pkgconfig
        echo "PKG_CONFIG_PATH=${PKG_CONFIG_PATH}" >> "${GITHUB_ENV}"
        ICU_VER=$(pkg-config --modversion icu-i18n)
        echo "ICU_VER=${ICU_VER}"
        echo "ICU_VER=${ICU_VER}" >> "${GITHUB_ENV}"
    - name: Install PyTorch
      shell: bash -l {0}
      run: |
        python -m pip install --cpuonly light-the-torch
        ltt install torch
    # - name: Install dependencies
    #   shell: bash -l {0}
    #   env:
    #     SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL: True
    #   run: |
    #     python -m pip install -r docker_requirements.txt
    - name: Install PyThaiNLP
      shell: bash -l {0}
      run: |
        python -m pip install .[full]
        python -m nltk.downloader omw-1.4
    - name: Test
      shell: bash -l {0}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_SERVICE_NAME: github
      run: |
        coverage run -m unittest discover
        coveralls
