name: Unit test and code coverage (Ubuntu)

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.yml'
      - 'docs/**'
  pull_request:
    branches:
      - dev
    paths-ignore:
      - '**.md'
      - '**.yml'
      - 'docs/**'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-24.04"]
        python-version: ["3.9"]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install build tools
      run: |
        python -m pip install --upgrade "pip<24.1" setuptools
        python -m pip install coverage coveralls pytest
    # - name: Install dependencies
    #   env:
    #     SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL: True
    #   run: |
    #     python -m pip install -r docker_requirements.txt
    - name: Install PyThaiNLP
      run: |
        python -m pip install .[full]
        python -m nltk.downloader omw-1.4
    - name: Test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_SERVICE_NAME: github
      run: |
        coverage run -m unittest discover
        coveralls
