name: Unit test and code coverage (MacOS)

on:
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
#       - '**.yml'
  pull_request:
    branches:
      - dev
    paths-ignore:
      - '**.md'
      - '**.yml'
      - 'docs/**'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        python-version: ["3.9"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false
        auto-update-conda: true
    - name: Show environment
      shell: powershell
      run: |
        conda info
        conda list
    - name: Install build tools
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install coverage coveralls pytest
        conda install -c conda-forge icu
        conda install -c conda-forge pyicu
    - name: Install dependencies
      shell: bash -l {0}
      env:
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL: True
      run: |
        python -m pip install -r docker_requirements.txt
    - name: Install PyThaiNLP
      shell: bash -l {0}
      run: |
        python -m pip install .[full]
        python -m nltk.downloader omw-1.4
    - name: Test
      shell: bash -l {0}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_SERVICE_NAME: github
      run: |
        coverage run -m unittest discover
        coveralls
